-- MySQL Script generated by MySQL Workbench
-- Sun 27 Sep 2020 06:11:43 AM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fodie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fodie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fodie` DEFAULT CHARACTER SET latin1 ;
USE `fodie` ;

-- -----------------------------------------------------
-- Table `fodie`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fodie`.`user` ;

CREATE TABLE IF NOT EXISTS `fodie`.`user` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(45) NULL,
  `token` VARCHAR(64) NULL,
  `created_at` DATETIME NULL,
  `address` VARCHAR(100) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fodie`.`seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fodie`.`seller` ;

CREATE TABLE IF NOT EXISTS `fodie`.`seller` (
  `idseller` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fodie`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fodie`.`item` ;

CREATE TABLE IF NOT EXISTS `fodie`.`item` (
  `iditem` INT NOT NULL,
  `availability` TINYINT(1) NULL,
  `quantity` VARCHAR(10) NULL,
  `seller_username` VARCHAR(45) NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iditem`, `seller_username`, `user_username`),
  INDEX `fk_item_seller_idx` (`seller_username` ASC),
  INDEX `fk_item_user1_idx` (`user_username` ASC),
  CONSTRAINT `fk_item_seller`
    FOREIGN KEY (`seller_username`)
    REFERENCES `fodie`.`seller` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `fodie`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fodie`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fodie`.`image` ;

CREATE TABLE IF NOT EXISTS `fodie`.`image` (
  `idimage` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `uri` VARCHAR(255) NULL,
  `item_iditem` INT NOT NULL,
  PRIMARY KEY (`idimage`, `item_iditem`),
  INDEX `fk_image_item1_idx` (`item_iditem` ASC),
  CONSTRAINT `fk_image_item1`
    FOREIGN KEY (`item_iditem`)
    REFERENCES `fodie`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fodie`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fodie`.`size` ;

CREATE TABLE IF NOT EXISTS `fodie`.`size` (
  `idsize` INT NOT NULL,
  `size` VARCHAR(10) NOT NULL,
  `item_iditem` INT NOT NULL,
  PRIMARY KEY (`idsize`, `item_iditem`),
  INDEX `fk_size_item1_idx` (`item_iditem` ASC),
  CONSTRAINT `fk_size_item1`
    FOREIGN KEY (`item_iditem`)
    REFERENCES `fodie`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fodie`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fodie`.`rating` ;

CREATE TABLE IF NOT EXISTS `fodie`.`rating` (
  `idrating` INT NOT NULL,
  `rate` INT(11) NOT NULL,
  `item_iditem` INT NOT NULL,
  `user_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrating`, `item_iditem`, `user_username`),
  INDEX `fk_rating_item1_idx` (`item_iditem` ASC),
  INDEX `fk_rating_user1_idx` (`user_username` ASC),
  CONSTRAINT `fk_rating_item1`
    FOREIGN KEY (`item_iditem`)
    REFERENCES `fodie`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `fodie`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
